### ISSUE TITLE
Feature: add icons to advanced feature section

### ISSUE THREAD

**Issue by TAKANOME-DEV** [TAKANOME-DEV/BlogHive#23]
### Type of feature

🍕 Feature

### Current behavior

![advanced_features](https://user-images.githubusercontent.com/79809121/210831561-17f5c2e8-de3c-4521-9e2a-eb5b20800c36.png)

### Suggested solution

- Replace the text `Icon` with an icon from React Icons.
- Remove borders

:information_source:  Note:  Issue #22 needs to be resolved before this one

![advanced_features_xd](https://user-images.githubusercontent.com/79809121/210832563-008066ec-94ad-4382-98cb-739c42931eac.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jayanth-kumar-morem** [comment]
I would love to contribute. Can you assign me to this?

**Comment by TAKANOME-DEV** [comment]
Sure, feel free to drop any question you have

**Comment by jayanth-kumar-morem** [comment]
Hi @TAKANOME-DEV 

1. Removed the borders as mentioned.
2. react-icons don't have the exact icons mentioned in the [UI](https://www.figma.com/file/OI6kqMhO65Eh5LXC40uuOH/BlogHive?node-id=27%3A2&t=nqy5OoBrHYmzHPxf-0)
So, I downloaded the images from the [Figma UI design](https://www.figma.com/file/OI6kqMhO65Eh5LXC40uuOH/BlogHive?node-id=27%3A2&t=nqy5OoBrHYmzHPxf-0) and included them as Icons in the public folder in the client app
3. Here's the UI update implemented
![Screenshot from 2023-01-08 01-39-11](https://user-images.githubusercontent.com/64846852/211168656-7251abec-08bb-4358-b7f9-2c125ef7c2b8.png)
4. I'll wait for Issue #22 to get closed so that the styling and organization of the Icons will be uniform.

**Comment by TAKANOME-DEV** [comment]
Hey @jayanth-kumar-morem this looks great :fire: 
You can open a draft pr while waiting for #22

**Comment by jayanth-kumar-morem** [comment]
Hi @TAKANOME-DEV, I have raised a draft PR.
